# Generated by Django 5.1.3 on 2024-11-15 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Perception",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("health", models.IntegerField()),
            ],
            options={
                "verbose_name": "Perception",
                "verbose_name_plural": "Perceptions",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Pill"), (2, "Liquid")], default=1
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="Amount of pills")),
                ("dosage", models.IntegerField(verbose_name="Dosage")),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        default=0,
                    ),
                ),
                ("interval", models.DurationField(verbose_name="Interval")),
            ],
            options={
                "verbose_name": "Medication",
                "verbose_name_plural": "Medication",
                "ordering": ["name"],
                "unique_together": {("name",)},
            },
        ),
    ]
