# Generated by Django 5.1.3 on 2024-11-13 18:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Perception",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("health", models.IntegerField()),
            ],
            options={
                "verbose_name": "Perception",
                "verbose_name_plural": "Perceptions",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Pill"), (2, "Liquid")], default=1
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="Amount of pills")),
                ("dosage", models.IntegerField(verbose_name="Dosage")),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("MO", "Monday"),
                            ("TU", "Tuesday"),
                            ("WE", "Wednesday"),
                            ("TH", "Thursday"),
                            ("FR", "Friday"),
                            ("SA", "Saturday"),
                            ("SU", "Sunday"),
                        ],
                        default="MO",
                        max_length=2,
                    ),
                ),
                ("interval", models.DurationField(verbose_name="Interval")),
            ],
            options={
                "verbose_name": "Medication",
                "verbose_name_plural": "Medication",
                "ordering": ["name"],
                "unique_together": {("name",)},
            },
        ),
    ]
