# Generated by Django 5.1.3 on 2024-11-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MedApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medication",
            name="day",
        ),
        migrations.RemoveField(
            model_name="medication",
            name="interval",
        ),
        migrations.AlterField(
            model_name="medication",
            name="dosage",
            field=models.IntegerField(verbose_name="Dosage to take"),
        ),
        migrations.CreateModel(
            name="DosingTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("time", models.TimeField(verbose_name="Time")),
            ],
            options={
                "verbose_name": "Dosing Time",
                "verbose_name_plural": "Dosing Times",
                "ordering": ["name"],
                "unique_together": {("name",)},
            },
        ),
        migrations.AddField(
            model_name="medication",
            name="time",
            field=models.ManyToManyField(
                to="MedApp.dosingtime", verbose_name="Dosing Times"
            ),
        ),
        migrations.CreateModel(
            name="Weekdays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("number", models.IntegerField()),
            ],
            options={
                "verbose_name": "Weekday",
                "verbose_name_plural": "Weekdays",
                "ordering": ["name"],
                "unique_together": {("name",)},
            },
        ),
        migrations.AddField(
            model_name="medication",
            name="days",
            field=models.ManyToManyField(to="MedApp.weekdays", verbose_name="Weekdays"),
        ),
    ]
