# Generated by Django 5.1.3 on 2024-11-25 21:07

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MedApp", "0002_remove_medication_day_remove_medication_interval_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dosingtime",
            options={
                "ordering": ["time"],
                "verbose_name": "Dosing Time",
                "verbose_name_plural": "Dosing Times",
            },
        ),
        migrations.AlterModelOptions(
            name="weekdays",
            options={
                "ordering": ["number"],
                "verbose_name": "Weekday",
                "verbose_name_plural": "Weekdays",
            },
        ),
        migrations.AlterField(
            model_name="medication",
            name="amount",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Amount of pills in stock",
            ),
        ),
        migrations.AlterField(
            model_name="medication",
            name="dosage",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Dosage to take",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dosingtime",
            unique_together={("time",)},
        ),
        migrations.AlterUniqueTogether(
            name="weekdays",
            unique_together={("number",)},
        ),
        migrations.CreateModel(
            name="CalendarDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "medication",
                    models.ManyToManyField(
                        to="MedApp.medication", verbose_name="Medication"
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar Day",
                "verbose_name_plural": "Calendar Days",
                "ordering": ["date"],
                "unique_together": {("date",)},
            },
        ),
    ]
