# Generated by Django 5.1.3 on 2024-11-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MedApp", "0003_alter_dosingtime_options_alter_weekdays_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarday",
            name="medication",
            field=models.ManyToManyField(
                blank=True, null=True, to="MedApp.medication", verbose_name="Medication"
            ),
        ),
    ]
