# Generated by Django 5.1.3 on 2024-11-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MedApp", "0004_alter_calendarday_medication"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="perception",
            options={
                "ordering": ["-date"],
                "verbose_name": "Perception",
                "verbose_name_plural": "Perceptions",
            },
        ),
        migrations.AlterField(
            model_name="calendarday",
            name="medication",
            field=models.ManyToManyField(
                blank=True, to="MedApp.medication", verbose_name="Medication"
            ),
        ),
        migrations.AlterField(
            model_name="medication",
            name="type",
            field=models.IntegerField(choices=[(1, "Pill"), (2, "ml")], default=1),
        ),
    ]
