# Generated by Django 5.1.3 on 2024-12-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MedApp", "0005_alter_perception_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medication",
            name="enddate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
